name: Test

on: [push, pull_request]

jobs:
  Sonarless-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sonarless Scan
        uses: gitricko/sonarless@v1.1
        with:
          sonar-source-path: '.'
          sonar-metrics-path: './sonarqube-results.json'

      - name: Check Sonar Metrics
        run: |
          echo "Checking for 0 vulnerabilities in Sonar Metrics JSON"
          VULN=$(cat ./sonarqube-results.json | jq -r '.component.measures[] | select(.metric == "vulnerabilities").value')
          echo "# of vulnerabilities = ${VULN}"
          [ "${VULN}" -eq "0" ]

  Test-Epinio-Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y apache2 apache2-utils
          ./makefile.sh install-dependencies
          
      - name: Install Epinio
        run: |
          ./makefile.sh install
          
