name: Test

on: [push, pull_request]

jobs:
  Sonarless-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sonarless Scan
        uses: gitricko/sonarless@v1.1
        with:
          sonar-source-path: '.'

  Test-Epinio-Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y apache2 apache2-utils
          ./makefile install-dependencies
          
      - name: Install Epinio
        run: |
          ./makefile install
          
